// import { Check } from "lucide-react"

import { ApplicationItem } from "@/components/application-item"
import { ProductContactSection } from "@/components/product-contact-section"
import categoryBbatsImg from "@/assets/images/bbats_bg.jpg"
import eseaRecImg from "@/assets/images/biobats.png"
import { DetailPageGate } from "@/components/DetailPageGate";

import app1Img from "@/assets/images/biobats.png"
import app2Img from "@/assets/images/biobats2.png"
import app3Img from "@/assets/images/biobats3.png"
import networkImg from "@/assets/images/bbats_network.png"

export default function DetailBbatsPage() {
  return (
    <DetailPageGate>
      <div className="pt-16">
        <section className="py-24 lg:py-32">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            {/* 제목 */}
            <div className="mb-12 text-center">
              <h1 className="text-5xl font-semibold tracking-tight text-foreground">BIOBATS</h1>
            </div>

            {/* 소제목 */}
            <div className="mb-8 text-center">
              <p className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">Smart Biological Detection & Early Warning System</p>
            </div>
          </div>

          {/* Full-width Hero Image */}
          <div className="w-full mb-12">
            <img
              src={categoryBbatsImg}
              alt="BIOBATS"
              className="w-full h-auto object-cover"
            />
          </div>

          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="max-w-4xl mx-auto text-center">
              <p className="text-2xl lg:text-4xl font-medium text-foreground leading-relaxed">
                Smart Biological Detection & Early Warning System
              </p>
            </div>
          </div>
        </section>

        {/* WHAT IS GoldenBat-EWS? */}
        <section className="py-24 lg:py-32 bg-card border-t border-border">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="max-w-4xl mx-auto">
              <h2 className="text-3xl font-semibold tracking-tight text-foreground mb-6">WHAT IS BIOBATS?</h2>
              <p className="text-lg text-muted-foreground leading-relaxed">
              Having experienced the COVID-19 pandemic, our society has come to fully recognize the dangers of airborne infectious diseases. New viruses, harmful bacteria, and other biological threats spread rapidly through droplets and dust particles in the air, constantly endangering lives and, at times, leading to large-scale economic losses such as pandemics. </p>
              <p className="text-lg text-muted-foreground leading-relaxed">
              BioBats provides a one-stop solution that swiftly detects airborne biological threats including those encountered in daily life and those used in warfare through automatic collection, analysis, and alerting. As the first solution of its kind developed in Korea, it offers real-time monitoring and immediate early warnings, delivering a new level of protection to our everyday lives.
              </p>

            </div>
          </div>
        </section>

        {/* 사진 섹션 */}
        <section className="border-t border-border">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="w-full">
              <img
                src={eseaRecImg}
                alt="GoldenBat-EWS"
                className="w-full h-auto object-cover rounded-lg"
                // style={{
                //   filter: "invert(1) brightness(2)", // 대충 검은색을 흰색처럼
                //   mixBlendMode: "difference",
                // }}
              />
            </div>
          </div>
        </section>




        <section className="py-24 lg:py-32 bg-card border-t border-border">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="max-w-4xl mx-auto">
              <h2 className="text-3xl font-semibold tracking-tight text-foreground mb-6">Sample transfer technology using laminar flow</h2>
              <p className="text-lg text-muted-foreground leading-relaxed">
              It is a technology that accurately moves sample particles to the designated position, and it is necessary to accurately collide the particles with the laser of the fluorescence measurement.</p>
              <p className="text-lg text-muted-foreground leading-relaxed">
              Laminar flow must be generated by adjusting the speed of the pump so that the inside of the fluorescence measurement is not polluted and turbulent flow is not generated.
              </p>
              <p className="text-lg text-muted-foreground leading-relaxed">
              The velocity of a fluid can be measured using a point proportional to the difference in pressure.
              </p>

            </div>
          </div>
        </section>


        
        <section className="py-24 lg:py-32 bg-card border-t border-border">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="max-w-4xl mx-auto">
              <h2 className="text-3xl font-semibold tracking-tight text-foreground mb-6">High-sensitivity fluorescence measurement & signal processing technology</h2>
              <p className="text-lg text-muted-foreground leading-relaxed">
              Reduced use of lenses to minimize system size
Structural design to make the detector as close to the light source as possible to maximize measurement efficiency
Analysis of wide distribution of particles ranging in size from 0.3 to 10 ㎛ using multiple detec tors to maximize measurement efficiency
Determining the presence of a wide range of biological substances by measuring fluorescence signals with wavelengths of 450 nm</p>

            </div>
          </div>
        </section>
        {/* KEY Benefits */}
        {/* <section className="py-24 lg:py-32 border-t border-border">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="max-w-2xl mb-16">
              <h2 className="text-3xl font-semibold tracking-tight text-foreground">KEY FEATURES</h2>
            </div>

            <div className="">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="flex items-start gap-3 py-3">
                  <Check className="h-5 w-5 text-foreground mt-0.5 flex-shrink-0" />
                  <span className="text-base text-foreground">24/7 chemical detection (CWA/TICs)</span>
                </div>

                <div className="flex items-start gap-3 py-3">
                  <Check className="h-5 w-5 text-foreground mt-0.5 flex-shrink-0" />
                  <span className="text-base text-foreground">Gamma-ray and Neutron detection</span>
                </div>

                <div className="flex items-start gap-3 py-3">
                  <Check className="h-5 w-5 text-foreground mt-0.5 flex-shrink-0" />
                  <span className="text-base text-foreground">Versatile communication and connectivity</span>
                </div>

                <div className="flex items-start gap-3 py-3">
                  <Check className="h-5 w-5 text-foreground mt-0.5 flex-shrink-0" />
                  <span className="text-base text-foreground">Local display with full system status</span>
                </div>

                <div className="flex items-start gap-3 py-3">
                  <Check className="h-5 w-5 text-foreground mt-0.5 flex-shrink-0" />
                  <span className="text-base text-foreground">Built-in maintenance & instruction tools for operator guidance</span>
                </div>

                <div className="flex items-start gap-3 py-3">
                  <Check className="h-5 w-5 text-foreground mt-0.5 flex-shrink-0" />
                  <span className="text-base text-foreground">Robust design for indoor & outdoor applications</span>
                </div>

                <div className="flex items-start gap-3 py-3">
                  <Check className="h-5 w-5 text-foreground mt-0.5 flex-shrink-0" />
                  <span className="text-base text-foreground">Integrate to 3rd party systems (Modbus interface)</span>
                </div>

                <div className="flex items-start gap-3 py-3">
                  <Check className="h-5 w-5 text-foreground mt-0.5 flex-shrink-0" />
                  <span className="text-base text-foreground">Automatic relay control</span>
                </div>

                <div className="flex items-start gap-3 py-3 md:col-span-2">
                  <Check className="h-5 w-5 text-foreground mt-0.5 flex-shrink-0" />
                  <span className="text-base text-foreground">OCompatible with previous Environics systems</span>
                </div>

                <div className="flex items-start gap-3 py-3 md:col-span-2">
                  <Check className="h-5 w-5 text-foreground mt-0.5 flex-shrink-0" />
                  <span className="text-base text-foreground">Online software updates available</span>
                </div>
              </div>
            </div>
          </div>
        </section> */}

        <section className="py-24 lg:py-32 border-t border-border">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="max-w-4xl mb-16">
            <h2 className="text-3xl font-semibold tracking-tight text-foreground mb-6">System Configuration</h2>
            </div>
            <div>
            <div className="w-full flex justify-center">
              <img
                src={networkImg}
                alt="GoldenBat-EWS"
                className="m-auto h-auto object-cover rounded-lg"
                // style={{
                //   filter: "invert(1) brightness(2)", // 대충 검은색을 흰색처럼
                //   mixBlendMode: "difference",
                // }}
              />
            </div>
            </div>
          </div>
        </section>


        {/* Specifications */}
        <section className="py-24 lg:py-32 bg-card border-t border-border">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="max-w-2xl mb-16">
              <h2 className="text-3xl font-semibold tracking-tight text-foreground">Specifications</h2>
            </div>

            <div className="space-y-12">
              {/* Air Collection */}
              <div>
                <h3 className="text-2xl font-semibold text-foreground mb-6">Air Collection</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="p-6 bg-background border border-border rounded-lg">
                    <h4 className="text-lg font-medium text-foreground mb-3">Collection air volume</h4>
                    <p className="text-sm text-muted-foreground">15L/Minute</p>
                  </div>

                  <div className="p-6 bg-background border border-border rounded-lg">
                    <h4 className="text-lg font-medium text-foreground mb-3">Particle size</h4>
                    <p className="text-sm text-muted-foreground">≤10μm</p>
                  </div>

                  <div className="p-6 bg-background border border-border rounded-lg">
                    <h4 className="text-lg font-medium text-foreground mb-3">Particle concentration ratio</h4>
                    <p className="text-sm text-muted-foreground">More than 10times</p>
                  </div>
                </div>
              </div>

              {/* Measurement */}
              <div>
                <h3 className="text-2xl font-semibold text-foreground mb-6">Measurement</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="p-6 bg-background border border-border rounded-lg">
                    <h4 className="text-lg font-medium text-foreground mb-3">Measurement method</h4>
                    <p className="text-sm text-muted-foreground">Fluorescence</p>
                  </div>

                  <div className="p-6 bg-background border border-border rounded-lg">
                    <h4 className="text-lg font-medium text-foreground mb-3">Light Source</h4>
                    <p className="text-sm text-muted-foreground">450nm</p>
                  </div>

                  <div className="p-6 bg-background border border-border rounded-lg">
                    <h4 className="text-lg font-medium text-foreground mb-3">Classification</h4>
                    <p className="text-sm text-muted-foreground">Virus, Bacteria</p>
                  </div>
                </div>
              </div>

              {/* Physical Considerations */}
              <div>
                <h3 className="text-2xl font-semibold text-foreground mb-6">Physical Considerations</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="p-6 bg-background border border-border rounded-lg">
                    <h4 className="text-lg font-medium text-foreground mb-3">Communication</h4>
                    <p className="text-sm text-muted-foreground">Ethernet, Wi-Fi, Bluetooth</p>
                  </div>

                  <div className="p-6 bg-background border border-border rounded-lg">
                    <h4 className="text-lg font-medium text-foreground mb-3">Display</h4>
                    <p className="text-sm text-muted-foreground">10.1" touch screen display</p>
                  </div>

                  <div className="p-6 bg-background border border-border rounded-lg">
                    <h4 className="text-lg font-medium text-foreground mb-3">Power</h4>
                    <p className="text-sm text-muted-foreground">External 110 / 220 vac</p>
                  </div>

                  <div className="p-6 bg-background border border-border rounded-lg">
                    <h4 className="text-lg font-medium text-foreground mb-3">Size</h4>
                    <p className="text-sm text-muted-foreground">W339 x H510 x D250 mm</p>
                  </div>

                  <div className="p-6 bg-background border border-border rounded-lg">
                    <h4 className="text-lg font-medium text-foreground mb-3">Weight</h4>
                    <p className="text-sm text-muted-foreground">Approx. 12.6kg</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="py-24 lg:py-32 border-t border-border">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="max-w-4xl mb-16">
            <h2 className="text-3xl font-semibold tracking-tight text-foreground mb-6">Figures</h2>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              <ApplicationItem
                imageSrc={app1Img}
                imageAlt="Application 1"
                title="Figure 1"
                isFull
              />
              <ApplicationItem
                imageSrc={app2Img}
                imageAlt="Application 2"
                title="Figure 2"
                isFull
              />
              <ApplicationItem
                imageSrc={app3Img}
                imageAlt="Application 3"
                title="Figure 3"
                isFull
              />
            </div>
          </div>
        </section>
        <ProductContactSection />
    </div>
    </DetailPageGate>
  )
}
